In [1]:
import numpy as np
import pandas as pd

In [2]:
df= pd.read_csv("C:/Users/Hanieh/Desktop/projects/New folder (16)/Data/Customer_Data.csv")

In [3]:
df.head()

,Customer_ID,Gender,Age,Married,State,Number_of_Referrals,Tenure_in_Months,Value_Deal,Phone_Service,Multiple_Lines,...,Payment_Method,Monthly_Charge,Total_Charges,Total_Refunds,Total_Extra_Data_Charges,Total_Long_Distance_Charges,Total_Revenue,Customer_Status,Churn_Category,Churn_Reason
0,19877-DEL,Male,35,No,Delhi,7,27,NaN,Yes,No,...,Credit Card,65.6,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,58353-MAH,Female,45,Yes,Maharashtra,14,13,NaN,Yes,Yes,...,Credit Card,-4.0,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,25063-WES,Male,51,No,West Bengal,4,35,Deal 5,Yes,No,...,Bank Withdrawal,73.9,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,59787-KAR,Male,79,No,Karnataka,3,21,Deal 4,Yes,No,...,Bank Withdrawal,98.0,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,28544-TAM,Female,80,No,Tamil Nadu,3,8,NaN,Yes,No,...,Credit Card,83.9,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability

In [4]:
print("Shape:", df.shape)

Shape: (6418, 32)

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,6418.0,47.070739,16.703633,18.00,33.0000,46.000,60.0000,85.00
Number_of_Referrals,6418.0,7.427859,4.621519,0.00,3.0000,7.000,11.0000,15.00
Tenure_in_Months,6418.0,17.342786,10.576391,1.00,8.0000,16.000,27.0000,36.00
Monthly_Charge,6418.0,63.652867,31.188823,-10.00,30.5625,70.100,89.7500,118.75
Total_Charges,6418.0,2280.374858,2268.049985,18.80,395.7250,1396.125,3783.6000,8684.80
Total_Refunds,6418.0,1.924944,7.849083,0.00,0.0000,0.000,0.0000,49.79
Total_Extra_Data_Charges,6418.0,6.718604,24.722533,0.00,0.0000,0.000,0.0000,150.00
Total_Long_Distance_Charges,6418.0,748.703468,847.672844,0.00,70.8050,407.475,1182.9175,3564.72
Total_Revenue,6418.0,3033.871987,2866.505426,21.36,603.7425,2108.635,4801.5375,11979.34

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6418 entries, 0 to 6417
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Customer_ID                  6418 non-null   object
 1   Gender                       6418 non-null   object
 2   Age                          6418 non-null   int64
 3   Married                      6418 non-null   object
 4   State                        6418 non-null   object
 5   Number_of_Referrals          6418 non-null   int64
 6   Tenure_in_Months             6418 non-null   int64
 7   Value_Deal                   2870 non-null   object
 8   Phone_Service                6418 non-null   object
 9   Multiple_Lines               5796 non-null   object
 10  Internet_Service             6418 non-null   object
 11  Internet_Type                5028 non-null   object
 12  Online_Security              5028 non-null   object
 13  Online_Backup                5028 non-null   object
 14  Device_Protection_Plan       5028 non-null   object
 15  Premium_Support              5028 non-null   object
 16  Streaming_TV                 5028 non-null   object
 17  Streaming_Movies             5028 non-null   object
 18  Streaming_Music              5028 non-null   object
 19  Unlimited_Data               5028 non-null   object
 20  Contract                     6418 non-null   object
 21  Paperless_Billing            6418 non-null   object
 22  Payment_Method               6418 non-null   object
 23  Monthly_Charge               6418 non-null   float64
 24  Total_Charges                6418 non-null   float64
 25  Total_Refunds                6418 non-null   float64
 26  Total_Extra_Data_Charges     6418 non-null   int64
 27  Total_Long_Distance_Charges  6418 non-null   float64
 28  Total_Revenue                6418 non-null   float64
 29  Customer_Status              6418 non-null   object
 30  Churn_Category               1732 non-null   object
 31  Churn_Reason                 1732 non-null   object
dtypes: float64(5), int64(4), object(23)
memory usage: 1.6+ MB

In [7]:
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    print(f"\n{col}")
    print(df[col].value_counts())

Customer_ID
Customer_ID
19877-DEL    1
39561-KAR    1
75573-CHH    1
12079-MAH    1
85576-AND    1
            ..
12590-UTT    1
58383-AND    1
28167-UTT    1
27791-BIH    1
34476-TAM    1
Name: count, Length: 6418, dtype: int64

Gender
Gender
Female    4048
Male      2370
Name: count, dtype: int64

Married
Married
No     3223
Yes    3195
Name: count, dtype: int64

State
State
Uttar Pradesh      629
Tamil Nadu         600
Maharashtra        504
Karnataka          470
Haryana            398
Andhra Pradesh     395
West Bengal        368
Punjab             342
Bihar              336
Gujarat            335
Jammu & Kashmir    320
Madhya Pradesh     288
Telangana          281
Rajasthan          259
Kerala             200
Odisha             152
Assam              139
Delhi              127
Jharkhand          113
Uttarakhand         62
Chhattisgarh        59
Puducherry          41
Name: count, dtype: int64

Value_Deal
Value_Deal
Deal 2    758
Deal 5    738
Deal 4    540
Deal 1    469
Deal 3    365
Name: count, dtype: int64

Phone_Service
Phone_Service
Yes    5796
No      622
Name: count, dtype: int64

Multiple_Lines
Multiple_Lines
No     3082
Yes    2714
Name: count, dtype: int64

Internet_Service
Internet_Service
Yes    5028
No     1390
Name: count, dtype: int64

Internet_Type
Internet_Type
Fiber Optic    2764
DSL            1502
Cable           762
Name: count, dtype: int64

Online_Security
Online_Security
No     3204
Yes    1824
Name: count, dtype: int64

Online_Backup
Online_Backup
No     2820
Yes    2208
Name: count, dtype: int64

Device_Protection_Plan
Device_Protection_Plan
No     2817
Yes    2211
Name: count, dtype: int64

Premium_Support
Premium_Support
No     3172
Yes    1856
Name: count, dtype: int64

Streaming_TV
Streaming_TV
No     2556
Yes    2472
Name: count, dtype: int64

Streaming_Movies
Streaming_Movies
No     2520
Yes    2508
Name: count, dtype: int64

Streaming_Music
Streaming_Music
No     2766
Yes    2262
Name: count, dtype: int64

Unlimited_Data
Unlimited_Data
Yes    4334
No      694
Name: count, dtype: int64

Contract
Contract
Month-to-Month    3286
Two Year          1719
One Year          1413
Name: count, dtype: int64

Paperless_Billing
Paperless_Billing
Yes    3792
No     2626
Name: count, dtype: int64

Payment_Method
Payment_Method
Bank Withdrawal    3575
Credit Card        2494
Mailed Check        349
Name: count, dtype: int64

Customer_Status
Customer_Status
Stayed     4275
Churned    1732
Joined      411
Name: count, dtype: int64

Churn_Category
Churn_Category
Competitor         761
Attitude           301
Dissatisfaction    300
Price              196
Other              174
Name: count, dtype: int64

Churn_Reason
Churn_Reason
Competitor had better devices                289
Competitor made better offer                 274
Attitude of support person                   208
Don't know                                   124
Competitor offered more data                 106
Attitude of service provider                  93
Competitor offered higher download speeds     92
Price too high                                72
Product dissatisfaction                       71
Network reliability                           66
Long distance charges                         62
Service dissatisfaction                       61
Moved                                         45
Extra data charges                            34
Limited range of services                     33
Poor expertise of online support              30
Lack of affordable download/upload speed      28
Lack of self-service on Website               27
Poor expertise of phone support               12
Deceased                                       5
Name: count, dtype: int64

In [8]:
df.isnull().sum()

Customer_ID                       0
Gender                            0
Age                               0
Married                           0
State                             0
Number_of_Referrals               0
Tenure_in_Months                  0
Value_Deal                     3548
Phone_Service                     0
Multiple_Lines                  622
Internet_Service                  0
Internet_Type                  1390
Online_Security                1390
Online_Backup                  1390
Device_Protection_Plan         1390
Premium_Support                1390
Streaming_TV                   1390
Streaming_Movies               1390
Streaming_Music                1390
Unlimited_Data                 1390
Contract                          0
Paperless_Billing                 0
Payment_Method                    0
Monthly_Charge                    0
Total_Charges                     0
Total_Refunds                     0
Total_Extra_Data_Charges          0
Total_Long_Distance_Charges       0
Total_Revenue                     0
Customer_Status                   0
Churn_Category                 4686
Churn_Reason                   4686
dtype: int64

In [9]:
df.columns

Index(['Customer_ID', 'Gender', 'Age', 'Married', 'State',
       'Number_of_Referrals', 'Tenure_in_Months', 'Value_Deal',
       'Phone_Service', 'Multiple_Lines', 'Internet_Service', 'Internet_Type',
       'Online_Security', 'Online_Backup', 'Device_Protection_Plan',
       'Premium_Support', 'Streaming_TV', 'Streaming_Movies',
       'Streaming_Music', 'Unlimited_Data', 'Contract', 'Paperless_Billing',
       'Payment_Method', 'Monthly_Charge', 'Total_Charges', 'Total_Refunds',
       'Total_Extra_Data_Charges', 'Total_Long_Distance_Charges',
       'Total_Revenue', 'Customer_Status', 'Churn_Category', 'Churn_Reason'],
      dtype='object')

In [10]:
# =========================
# DATA CLEANING
# =========================

# fill missing values
df["Value_Deal"]             = df["Value_Deal"].fillna("None")
df["Multiple_Lines"]         = df["Multiple_Lines"].fillna("No")
df["Internet_Type"]          = df["Internet_Type"].fillna("None")
df["Online_Security"]        = df["Online_Security"].fillna("No")
df["Online_Backup"]          = df["Online_Backup"].fillna("No")
df["Device_Protection_Plan"] = df["Device_Protection_Plan"].fillna("No")
df["Premium_Support"]        = df["Premium_Support"].fillna("No")
df["Streaming_TV"]           = df["Streaming_TV"].fillna("No")
df["Streaming_Movies"]       = df["Streaming_Movies"].fillna("No")
df["Streaming_Music"]        = df["Streaming_Music"].fillna("No")
df["Unlimited_Data"]         = df["Unlimited_Data"].fillna("No")
df["Churn_Category"]         = df["Churn_Category"].fillna("Others")
df["Churn_Reason"]           = df["Churn_Reason"].fillna("Others")

In [11]:
print("\nNull Values After Cleaning:")
print(df.isnull().sum())

Null Values After Cleaning:
Customer_ID                    0
Gender                         0
Age                            0
Married                        0
State                          0
Number_of_Referrals            0
Tenure_in_Months               0
Value_Deal                     0
Phone_Service                  0
Multiple_Lines                 0
Internet_Service               0
Internet_Type                  0
Online_Security                0
Online_Backup                  0
Device_Protection_Plan         0
Premium_Support                0
Streaming_TV                   0
Streaming_Movies               0
Streaming_Music                0
Unlimited_Data                 0
Contract                       0
Paperless_Billing              0
Payment_Method                 0
Monthly_Charge                 0
Total_Charges                  0
Total_Refunds                  0
Total_Extra_Data_Charges       0
Total_Long_Distance_Charges    0
Total_Revenue                  0
Customer_Status                0
Churn_Category                 0
Churn_Reason                   0
dtype: int64

# FEATURE ENGINEERING

In [12]:
# Monthly Charge Range

def monthly_charge_range(charge):
    if charge < 20:    return "< 20"
    elif charge < 50:  return "20-50"
    elif charge < 100: return "50-100"
    else:              return "> 100"
    
df["Monthly_Charge_Range"] = df["Monthly_Charge"].apply(monthly_charge_range)

In [13]:
# Age Group

def age_group(age):
    if age < 20:   return "< 20"
    elif age < 36: return "20-35"
    elif age < 51: return "36-50"
    else:          return "> 50"

df["Age_Group"] = df["Age"].apply(age_group)
df["AgeGrp_Sorting"] = df["Age_Group"].map({"< 20": 1, "20-35": 2, "36-50": 3, "> 50": 4})

In [14]:
# Tenure Group

def tenure_group(tenure):
    if tenure < 6:    return "< 6 Months"
    elif tenure < 12: return "6-12 Months"
    elif tenure < 18: return "12-18 Months"
    elif tenure < 24: return "18-24 Months"
    else:             return ">= 24 Months"

df["Tenure_Group"] = df["Tenure_in_Months"].apply(tenure_group)
df["TenureGrp_Sorting"] = df["Tenure_Group"].map({"< 6 Months": 1, 
                                                  "6-12 Months": 2,
                                                  "12-18 Months": 3, 
                                                  "18-24 Months": 4, 
                                                  ">= 24 Months": 5})

In [15]:
sql_main_dataset = df.copy()

# now we create two data set that we will use later in machine learning before making churn status

In [16]:
#making twoو datasets based on "Churned", "Stayed" and the other based on Customer_Status == "Joined"

churn_data = df[df["Customer_Status"].isin(["Stayed", "Churned"])].copy()
join_data  = df[df["Customer_Status"] == "Joined"].copy()

In [61]:
# Create Churn_Status only for churn_data
# because join_data customers have not yet been classified as Churned or Stayed

churn_data["Churn_Status"] = churn_data["Customer_Status"].apply(
    lambda x: 1 if x == "Churned" else 0
)

print("\nChurn Data Shape:", churn_data.shape)
print("Join Data Shape:",   join_data.shape)
print("\nChurn Status Values:")
print(churn_data["Churn_Status"].value_counts())

Churn Data Shape: (6007, 38)
Join Data Shape: (411, 37)

Churn Status Values:
Churn_Status
0    4275
1    1732
Name: count, dtype: int64

In [62]:
# =========================
# Create the Services table
# =========================

# List of service-related columns
service_columns = [
    "Phone_Service", "Multiple_Lines", "Internet_Service",
    "Internet_Type", "Online_Security", "Online_Backup",
    "Device_Protection_Plan", "Premium_Support", "Streaming_TV",
    "Streaming_Movies", "Streaming_Music", "Unlimited_Data"
]

# Convert service columns from wide format to long format
prod_services = churn_data[["Customer_ID"] + service_columns].melt(id_vars="Customer_ID",
                                                                   var_name="Services",
                                                                   value_name="Status")

In [63]:
# =========================
# Save the processed datasets 
# =========================

# Save the historical customer data (Stayed + Churned)
churn_data.to_csv("C:/Users/Hanieh/Desktop/churn_data.csv", index=False)

# Save the new customers (Joined)
join_data.to_csv("C:/Users/Hanieh/Desktop/join_data.csv", index=False)

# Save the unpivoted services table
prod_services.to_csv("C:/Users/Hanieh/Desktop/prod_services.csv", index=False)

# Save main table for sql
sql_main_dataset.to_csv(r"C:/Users/Hanieh/Desktop/prod_customers.csv", index=False)


# Display a success message
print("\n files saved successfully!")

 files saved successfully!

# SEND TO SQL SERVER

In [64]:
from sqlalchemy import create_engine

server = "localhost"   
database = "churn11"

connection_string = (
    "mssql+pyodbc://@"
    f"{server}/{database}"
    "?driver=ODBC+Driver+17+for+SQL+Server"
    "&trusted_connection=yes"
)

engine = create_engine(connection_string)

# test connection
with engine.connect() as conn:
    print("Connection successful")

Connection successful

In [65]:
# MAIN TABLE (MOST IMPORTANT)
sql_main_dataset.to_sql("prod_customers", engine, if_exists="replace", index=False)

34